name = "PawsomeTracker"
uuid = "d3f98fa6-545d-4d4c-aa39-0a9eb18c40ca"
authors = ["Yakir Gagnon <12.yakir@gmail.com> and contributors"]
version = "1.0.3"

[deps]
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
Aqua = "0.8"
ColorTypes = "0.7, 0.8, 0.9, 0.10, 0.11, 0.12"
FixedPointNumbers = "0.5, 0.6, 0.7, 0.8"
ImageDraw = "0.1, 0.2"
ImageFiltering = "0.4, 0.5, 0.6, 0.7"
LinearAlgebra = "1"
OffsetArrays = "0.7, 0.8, 0.9, 0.10, 0.11, 1"
PaddedViews = "0.4, 0.5"
Statistics = "1"
StatsBase = "0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34"
Test = "1"
VideoIO = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageDraw = "4381153b-2b60-58ae-a1ba-fd683676385f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[targets]
test = ["Aqua", "ColorTypes", "FixedPointNumbers", "ImageDraw", "LinearAlgebra", "Statistics", "Test", "VideoIO"]
